export const COUNTER_INCREMENT         = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT         = 'COUNTER_DECREMENT'

export const FILE_UPLOAD_START         = 'FILE_UPLOAD_START'
export const FILE_UPLOAD_SUCCESS       = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_ERROR         = 'FILE_UPLOAD_ERROR'

export const FILE_CHECK_STATUS_START   = 'FILE_CHECK_STATUS_START'
export const FILE_CHECK_STATUS_SUCCESS = 'FILE_CHECK_STATUS_SUCCESS'
export const FILE_CHECK_STATUS_ERROR   = 'FILE_CHECK_STATUS_ERROR'