export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'

export const FETCH_STATUS_REQUEST = 'FETCH_STATUS_REQUEST'
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS'
export const FETCH_STATUS_FAILURE = 'FETCH_STATUS_FAILURE'

export const FILE_UPLOAD_START   = 'FILE_UPLOAD_START'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_ERROR   = 'FILE_UPLOAD_ERROR'